package com.hurenjieee.entity;

// Generated 2017-6-20 23:06:48 by Hibernate Tools 5.0.4.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.hurenjieee.core.BaseEntity;

/**
 * TestEntity generated by hbm2java
 */
@Entity
@Table(name = "test_entity",catalog = "hms")
public class TestEntity  extends BaseEntity{

    private String name;
    
    private Date   date;

    public TestEntity() {}

    @Column(name = "name")
    public String getName(){
        return this.name;
    }

    public void setName(String name){
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date",length = 19,insertable = false)
    public Date getDate(){
        return this.date;
    }

    public void setDate(Date date){
        this.date = date;
    }
}
