package com.hurenjieee.entity;
// Generated 2017-6-20 23:06:48 by Hibernate Tools 5.0.4.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestEntity generated by hbm2java
 */
@Entity
@Table(name = "test_entity",catalog = "hms")
public class TestEntity implements java.io.Serializable {

    private int    id;
    private String name;
    private Date   date;

    public TestEntity() {}

    public TestEntity(int id) {
        this.id = id;
    }

    public TestEntity(int id, String name, Date date) {
        this.id = id;
        this.name = name;
        this.date = date;
    }

    @Id

    @Column(name = "id",unique = true,nullable = false)
    public int getId(){
        return this.id;
    }

    public void setId(int id){
        this.id = id;
    }

    @Column(name = "name")
    public String getName(){
        return this.name;
    }

    public void setName(String name){
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date",length = 19)
    public Date getDate(){
        return this.date;
    }

    public void setDate(Date date){
        this.date = date;
    }

}
