    package com.hurenjieee.test.entity;

// Generated 2017-6-20 23:06:48 by Hibernate Tools 5.0.4.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.hurenjieee.core.BaseEntity;

/**
 * TestEntity generated by hbm2java
 */
@Entity
@Table(name = "test_entity",catalog = "hms")
public class TestEntity implements BaseEntity{

    
    @Id
    private Long id;

    private String uuid;

    @Column(name = "create_date")
    private Date createDate;

    @Column(name = "update_date")
    private Date updateDate;

    
    
    @Column(name = "name")
    private String name;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date",length = 19,insertable = false)
    private Date   date;

    public TestEntity() {}

    public String getName(){
        return this.name;
    }

    public void setName(String name){
        this.name = name;
    }

    public Date getDate(){
        return this.date;
    }

    public void setDate(Date date){
        this.date = date;
    }

    
    public Long getId(){
        return id;
    }

    
    public void setId(Long id){
        this.id = id;
    }

    
    public String getUuid(){
        return uuid;
    }

    
    public void setUuid(String uuid){
        this.uuid = uuid;
    }

    
    public Date getCreateDate(){
        return createDate;
    }

    
    public void setCreateDate(Date createDate){
        this.createDate = createDate;
    }

    
    public Date getUpdateDate(){
        return updateDate;
    }

    
    public void setUpdateDate(Date updateDate){
        this.updateDate = updateDate;
    }
    
    
}
